name: Lighthouse
on:
  schedule:
    - cron:  '40 14 * * *'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir /tmp/artifacts
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: /tmp/artifacts
        urls: 'https://www.americastestkitchen.com/,https://www.cookscountry.com/,https://www.cooksillustrated.com/,https://www.americastestkitchen.com/kids/home,https://www.americastestkitchen.com/articles/3991-recipe-brown-butter-soy-crispy-wings-infinite-sauce'
        slackWebhookUrl: ${{ secrets.LIGHTHOUSE_CHECK_WEBHOOK_URL }}
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts
